import { Course } from "./course.model";

export const courses: Course[] = [
	{
		id: '15459251a6d6b397565',
		title: 'Spring',
		subTitle: 'REST API',
		description: 'Commits that need to be pushed lorem ipsum dolor sit amet, consectetur adipiscing elit.',
		category: 'WEB',
		totalPoints: 500,
		earnedPoints: 250,
		length: 30,
		totalSteps: 11,
		activeStep: 11,
		updated: 'Jun 28, 2019',
		favorite: true
	},
	{
		id: '15459251a6d6b397565',
		title: 'Spring',
		subTitle: 'SECURITY',
		description: 'Commits that need to be pushed lorem ipsum dolor sit amet, consectetur adipiscing elit.',
		category: 'SPRING',
		totalPoints: 500,
		earnedPoints: 0,
		length: 60,
		totalSteps: 7,
		activeStep: 0,
		updated: 'Feb 22, 2020',
		favorite: false
	},
	{
		id: '15459251a6d6b397565',
		title: 'Java',
		subTitle: 'Java Basics',
		description: 'Commits that need to be pushed lorem ipsum dolor sit amet, consectetur adipiscing elit.',
		category: 'JAVA',
		totalPoints: 500,
		earnedPoints: 0,
		length: 30,
		totalSteps: 4,
		activeStep: 3,
		updated: 'Jun 1, 2019',
		favorite: false
	},
	{
		id: '15459251a6d6b397565',
		title: 'Spring',
		subTitle: 'OAuth2',
		description: 'Commits that need to be pushed lorem ipsum dolor sit amet, consectetur adipiscing elit.',
		category: 'SPRING',
		totalPoints: 500,
		earnedPoints: 0,
		length: 60,
		totalSteps: 11,
		activeStep: 5,
		updated: 'Jun 13, 2019',
		favorite: true
	},
	{
		id: '15459251a6d6b397565',
		title: 'Java',
		subTitle: 'Java 8',
		description: 'Commits that need to be pushed lorem ipsum dolor sit amet, consectetur adipiscing elit.',
		category: 'JAVA',
		totalPoints: 500,
		earnedPoints: 0,
		length: 30,
		totalSteps: 11,
		activeStep: 0,
		updated: 'Jun 14, 2019',
		favorite: false
	},
	{
		id: '15459251a6d6b397565',
		title: 'React',
		subTitle: 'React hooks',
		description: 'Commits that need to be pushed lorem ipsum dolor sit amet, consectetur adipiscing elit.',
		category: 'REACT',
		totalPoints: 500,
		earnedPoints: 500,
		length: 75,
		totalSteps: 11,
		activeStep: 11,
		updated: 'Jun 17, 2019',
		favorite: true
	},
	{
		id: '15459251a6d6b397565',
		title: 'Typescript',
		subTitle: 'Typescript',
		description: 'Commits that need to be pushed lorem ipsum dolor sit amet, consectetur adipiscing elit.',
		category: 'TYPESCRIPT',
		totalPoints: 500,
		earnedPoints: 0,
		length: 34,
		totalSteps: 11,
		activeStep: 0,
		updated: 'Jun 11, 2019',
		favorite: false
	},
	{
		id: '15459251a6d6b397565',
		title: 'Spring',
		subTitle: 'REST API',
		description: 'Commits that need to be pushed lorem ipsum dolor sit amet, consectetur adipiscing elit.',
		category: 'SPRING',
		totalPoints: 500,
		earnedPoints: 200,
		length: 30,
		totalSteps: 11,
		activeStep: 4,
		updated: 'Jun 28, 2017',
		favorite: true
	},
	{
		id: '15459251a6d6b397565',
		title: 'React',
		subTitle: 'Context',
		description: 'Commits that need to be pushed lorem ipsum dolor sit amet, consectetur adipiscing elit.',
		category: 'REACT',
		totalPoints: 500,
		earnedPoints: 200,
		length: 50,
		totalSteps: 11,
		activeStep: 0,
		updated: 'Jun 23, 2019',
		favorite: false
	},
	{
		id: '15459251a6d6b397565',
		title: 'Spring',
		subTitle: 'REST API',
		description: 'Commits that need to be pushed lorem ipsum dolor sit amet, consectetur adipiscing elit.',
		category: 'SPRING',
		totalPoints: 500,
		earnedPoints: 0,
		length: 45,
		totalSteps: 11,
		activeStep: 2,
		updated: 'Jun 3, 2019',
		favorite: false
	},
	{
		id: '15459251a6d6b397565',
		title: 'Spring',
		subTitle: 'Injection control',
		description: 'Commits that need to be pushed lorem ipsum dolor sit amet, consectetur adipiscing elit.',
		category: 'SPRING',
		totalPoints: 500,
		earnedPoints: 0,
		length: 45,
		totalSteps: 5,
		activeStep: 1,
		updated: 'Jun 18, 2019',
		favorite: true
	},
	{
		id: '15459251a6d6b397565',
		title: 'Spring',
		subTitle: 'REST API',
		description: 'Commits that need to be pushed lorem ipsum dolor sit amet, consectetur adipiscing elit.',
		category: 'SPRING',
		totalPoints: 500,
		earnedPoints: 0,
		length: 30,
		totalSteps: 11,
		activeStep: 4,
		updated: 'Jun 28, 2017',
		favorite: true
	},
	{
		id: '15459251a6d6b397565',
		title: 'Spring',
		subTitle: 'REST API',
		description: 'Commits that need to be pushed lorem ipsum dolor sit amet, consectetur adipiscing elit.',
		category: 'SPRING',
		totalPoints: 500,
		earnedPoints: 0,
		length: 30,
		totalSteps: 11,
		activeStep: 4,
		updated: 'Jun 28, 2017',
		favorite: true
	}
];
